/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LCD.h"
#include "Control.h"
#include "Status.h"
#include "In_0.h"
#include "In_0_aliases.h"
#include "In_1.h"
#include "In_1_aliases.h"
#include "In_2.h"
#include "In_2_aliases.h"
#include "Out_0.h"
#include "Out_0_aliases.h"
#include "In_3.h"
#include "In_3_aliases.h"
#include "Out_1.h"
#include "Out_1_aliases.h"
#include "Out_2.h"
#include "Out_2_aliases.h"
#include "Out_3.h"
#include "Out_3_aliases.h"
#include "timer_clock.h"
#include "Timer.h"
#include "isrTimer.h"
#include "Clock_1.h"
#include "Cross.h"
#include "Cross_aliases.h"
#include "Dimmer.h"
#include "Dimmer_aliases.h"
#include "isrCross.h"
#include "LCD_LCDPort.h"
#include "LCD_LCDPort_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

